### PR TITLE
Remove bad list from dns-blackhole.yml

### PR DESCRIPTION
**Pull request by jchristi**
`https://easylist.to/easylist/easylist.txt` ends up blocking way too many domains that should not be blocked (google.com, yahoo.com, bing.com, duckduckgo.com). It pretty much broke my internet connectivity.

### CODE REVIEW

**Comment by olivier-mauras** [comment]
Well the fact that some hosts that you consider OK are in a community supported list, doesn't necessarily make the list *bad*.
If you want to access hosts that are blocked by a list, just add them to your whitelist - that's why the feature exists! - or if you feel like removing the list completely, just remove it from your own config. There's no point in removing for everyone though...

**Comment by jchristi** [comment]
What I'm trying to say is that it is blocking ALL dns requests. I was unable to make ANY dns requests. It broke my network.

**Comment by jchristi** [comment]
Also, it is a community supported *URL* blacklist, not a DNS address blacklist. Your code is trying to translate it into one but something isn't working properly.

**Comment by olivier-mauras** [comment]
Let me understand you, you mean that unbound or whichever DNS server you use stopped answering _ANY_ query, even for domains that were not listed in your blackhole.zone file? Is that right?

I can't reproduce that behaviour with an empty whitelist ...

**Pull request closed without merging**
